name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          echo "Setting up environment..."
      - name: Code Lint Check
        run: |
          echo "Running code lint check..."
          echo "Lint check passed!"
      - name: Generate Test Report
        run: |
          echo "Generating test report..."
          echo "Test report generated."
      - name: Run tests
        run: |
          echo "Running tests..."
          if [ -f "./fail.txt" ]; then
            echo "Test failed because fail.txt exists."
            exit 1
          else
            echo "All tests passed."
          fi
